//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourceLibrary.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string addButton {
            get {
                return ResourceManager.GetString("addButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during adding Complaint. Check data or contact to Admin..
        /// </summary>
        public static string addComplainError {
            get {
                return ResourceManager.GetString("addComplainError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product Warehouse to this Warehouse..
        /// </summary>
        public static string AddProductWarehouse {
            get {
                return ResourceManager.GetString("AddProductWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse address.
        /// </summary>
        public static string AddressOfWarehouse {
            get {
                return ResourceManager.GetString("AddressOfWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Safety Point to this group.
        /// </summary>
        public static string AddSafetyPointToSafetyPointGroup {
            get {
                return ResourceManager.GetString("AddSafetyPointToSafetyPointGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service Warehouse to this Warehouse..
        /// </summary>
        public static string AddServiceWarehouse {
            get {
                return ResourceManager.GetString("AddServiceWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse created successful..
        /// </summary>
        public static string AddWarehouseSuccessful {
            get {
                return ResourceManager.GetString("AddWarehouseSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of attribute.
        /// </summary>
        public static string attributeTypeName {
            get {
                return ResourceManager.GetString("attributeTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value.
        /// </summary>
        public static string attributeValue {
            get {
                return ResourceManager.GetString("attributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account number.
        /// </summary>
        public static string bankAccountNumber {
            get {
                return ResourceManager.GetString("bankAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------Choose customer------.
        /// </summary>
        public static string choiceCustomer {
            get {
                return ResourceManager.GetString("choiceCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select role for the employee.
        /// </summary>
        public static string choicesRoles {
            get {
                return ResourceManager.GetString("choicesRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose warehouse to put item to..
        /// </summary>
        public static string choicesWarehouses {
            get {
                return ResourceManager.GetString("choicesWarehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose store first..
        /// </summary>
        public static string chooseStoreFirst {
            get {
                return ResourceManager.GetString("chooseStoreFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice client.
        /// </summary>
        public static string client {
            get {
                return ResourceManager.GetString("client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Address.
        /// </summary>
        public static string clientAddress {
            get {
                return ResourceManager.GetString("clientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Info.
        /// </summary>
        public static string clientInfo {
            get {
                return ResourceManager.GetString("clientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        public static string clientName {
            get {
                return ResourceManager.GetString("clientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name field is required.
        /// </summary>
        public static string clientNameRequiredErrorMsg {
            get {
                return ResourceManager.GetString("clientNameRequiredErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client NIP.
        /// </summary>
        public static string clientNIP {
            get {
                return ResourceManager.GetString("clientNIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trza commitować resources bo potem ludziom błędy się sypią.
        /// </summary>
        public static string collectionOfWarehouses {
            get {
                return ResourceManager.GetString("collectionOfWarehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords doesn&apos;t match.
        /// </summary>
        public static string comparePasswords {
            get {
                return ResourceManager.GetString("comparePasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add complaint success.
        /// </summary>
        public static string complaintAddSuccess {
            get {
                return ResourceManager.GetString("complaintAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint description.
        /// </summary>
        public static string complaintDescription {
            get {
                return ResourceManager.GetString("complaintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint for this item is already made..
        /// </summary>
        public static string complaintExists {
            get {
                return ResourceManager.GetString("complaintExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string createButton {
            get {
                return ResourceManager.GetString("createButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred. Please try again ..
        /// </summary>
        public static string createdError {
            get {
                return ResourceManager.GetString("createdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Product Warehouse.
        /// </summary>
        public static string CreateProductWarehouse {
            get {
                return ResourceManager.GetString("CreateProductWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name for new Product Warehouse.
        /// </summary>
        public static string CreateProductWarehouseName {
            get {
                return ResourceManager.GetString("CreateProductWarehouseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Service Warehouse.
        /// </summary>
        public static string CreateServiceWarehouse {
            get {
                return ResourceManager.GetString("CreateServiceWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name for new Service Warehouse.
        /// </summary>
        public static string CreateServiceWarehouseName {
            get {
                return ResourceManager.GetString("CreateServiceWarehouseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of Creation.
        /// </summary>
        public static string creationPlace {
            get {
                return ResourceManager.GetString("creationPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Place field is required.
        /// </summary>
        public static string creationPlaceRequiredErrorMsg {
            get {
                return ResourceManager.GetString("creationPlaceRequiredErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of creation.
        /// </summary>
        public static string creationTime {
            get {
                return ResourceManager.GetString("creationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Time is required..
        /// </summary>
        public static string creationTimeRequiredErrorMsg {
            get {
                return ResourceManager.GetString("creationTimeRequiredErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency of PDF.
        /// </summary>
        public static string currency {
            get {
                return ResourceManager.GetString("currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer address.
        /// </summary>
        public static string customerAddress {
            get {
                return ResourceManager.GetString("customerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is not Firm. You can&apos;t print facture for this Customer..
        /// </summary>
        public static string customerIsNotFirmForFacture {
            get {
                return ResourceManager.GetString("customerIsNotFirmForFacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name.
        /// </summary>
        public static string customerName {
            get {
                return ResourceManager.GetString("customerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time when delivered.
        /// </summary>
        public static string deliveredTime {
            get {
                return ResourceManager.GetString("deliveredTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string displayButton {
            get {
                return ResourceManager.GetString("displayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution not created. Please check inserted data or contact to administrator..
        /// </summary>
        public static string distributionAddError {
            get {
                return ResourceManager.GetString("distributionAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution is already performed.
        /// </summary>
        public static string distributionAlreadyPerformed {
            get {
                return ResourceManager.GetString("distributionAlreadyPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selected items. Please choose distribution items..
        /// </summary>
        public static string distributionChooseItemsError {
            get {
                return ResourceManager.GetString("distributionChooseItemsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution create time.
        /// </summary>
        public static string distributionCreateTime {
            get {
                return ResourceManager.GetString("distributionCreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution creator name.
        /// </summary>
        public static string distributionCreatorName {
            get {
                return ResourceManager.GetString("distributionCreatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add distribution customer.
        /// </summary>
        public static string distributionCustomerAdd {
            get {
                return ResourceManager.GetString("distributionCustomerAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution date.
        /// </summary>
        public static string distributionDate {
            get {
                return ResourceManager.GetString("distributionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution id.
        /// </summary>
        public static string distributionId {
            get {
                return ResourceManager.GetString("distributionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add items. You can change item Quantity..
        /// </summary>
        public static string distributionItemsAdd {
            get {
                return ResourceManager.GetString("distributionItemsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform distribution.
        /// </summary>
        public static string distributionPerform {
            get {
                return ResourceManager.GetString("distributionPerform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution performed successfully.
        /// </summary>
        public static string distributionPerformedSuccessful {
            get {
                return ResourceManager.GetString("distributionPerformedSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution not performed.
        /// </summary>
        public static string distributionPerformedUnsuccessful {
            get {
                return ResourceManager.GetString("distributionPerformedUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose distribution provider.
        /// </summary>
        public static string distributionProviderAdd {
            get {
                return ResourceManager.GetString("distributionProviderAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution state.
        /// </summary>
        public static string distributionState {
            get {
                return ResourceManager.GetString("distributionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution time.
        /// </summary>
        public static string distributionTime {
            get {
                return ResourceManager.GetString("distributionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total items cost.
        /// </summary>
        public static string distributionTotalCost {
            get {
                return ResourceManager.GetString("distributionTotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error accured. Please try again later..
        /// </summary>
        public static string editError {
            get {
                return ResourceManager.GetString("editError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address email.
        /// </summary>
        public static string emailAddress {
            get {
                return ResourceManager.GetString("emailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of payment expiration.
        /// </summary>
        public static string expirationTime {
            get {
                return ResourceManager.GetString("expirationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of payment is required..
        /// </summary>
        public static string expirationTimeRequiredErrorMsg {
            get {
                return ResourceManager.GetString("expirationTimeRequiredErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string factureItemName {
            get {
                return ResourceManager.GetString("factureItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item PKWiU.
        /// </summary>
        public static string factureItemPKWiU {
            get {
                return ResourceManager.GetString("factureItemPKWiU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Price Per Unit.
        /// </summary>
        public static string factureItemPricePerUnit {
            get {
                return ResourceManager.GetString("factureItemPricePerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Price Tax.
        /// </summary>
        public static string factureItemPriceTax {
            get {
                return ResourceManager.GetString("factureItemPriceTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Price Without Tax.
        /// </summary>
        public static string factureItemPriceWithoutTax {
            get {
                return ResourceManager.GetString("factureItemPriceWithoutTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Price With Tax.
        /// </summary>
        public static string factureItemPriceWithTax {
            get {
                return ResourceManager.GetString("factureItemPriceWithTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Quantity.
        /// </summary>
        public static string factureItemQuantity {
            get {
                return ResourceManager.GetString("factureItemQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Sale Type.
        /// </summary>
        public static string factureItemSaleType {
            get {
                return ResourceManager.GetString("factureItemSaleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Tax.
        /// </summary>
        public static string factureItemTax {
            get {
                return ResourceManager.GetString("factureItemTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number.
        /// </summary>
        public static string factureNr {
            get {
                return ResourceManager.GetString("factureNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm.
        /// </summary>
        public static string firm {
            get {
                return ResourceManager.GetString("firm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm Address.
        /// </summary>
        public static string firmAddress {
            get {
                return ResourceManager.GetString("firmAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm Bank Account Number.
        /// </summary>
        public static string firmBankAccountNumber {
            get {
                return ResourceManager.GetString("firmBankAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm Bank Info.
        /// </summary>
        public static string firmBankInfo {
            get {
                return ResourceManager.GetString("firmBankInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm Info.
        /// </summary>
        public static string firmInfo {
            get {
                return ResourceManager.GetString("firmInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm Name.
        /// </summary>
        public static string firmName {
            get {
                return ResourceManager.GetString("firmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm NIP.
        /// </summary>
        public static string firmNIP {
            get {
                return ResourceManager.GetString("firmNIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm Phone.
        /// </summary>
        public static string firmPhone {
            get {
                return ResourceManager.GetString("firmPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm field is required.
        /// </summary>
        public static string firmRequiredErrorMsg {
            get {
                return ResourceManager.GetString("firmRequiredErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facture Id.
        /// </summary>
        public static string idFacture {
            get {
                return ResourceManager.GetString("idFacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Id.
        /// </summary>
        public static string idFactureItem {
            get {
                return ResourceManager.GetString("idFactureItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm Id.
        /// </summary>
        public static string idFirm {
            get {
                return ResourceManager.GetString("idFirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment In Words.
        /// </summary>
        public static string inWords {
            get {
                return ResourceManager.GetString("inWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum With Tax In Words field is required.
        /// </summary>
        public static string inWordsRequiredErrorMsg {
            get {
                return ResourceManager.GetString("inWordsRequiredErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Issuer.
        /// </summary>
        public static string issuer {
            get {
                return ResourceManager.GetString("issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer field is required.
        /// </summary>
        public static string issuerRequiredErrorMsg {
            get {
                return ResourceManager.GetString("issuerRequiredErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new attribute to Item.
        /// </summary>
        public static string itemAddAttribute {
            get {
                return ResourceManager.GetString("itemAddAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Type of Item.
        /// </summary>
        public static string itemChoicesItemType {
            get {
                return ResourceManager.GetString("itemChoicesItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Sale type of Item.
        /// </summary>
        public static string itemChoicesSaleType {
            get {
                return ResourceManager.GetString("itemChoicesSaleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Tax of Item.
        /// </summary>
        public static string itemChoicesTax {
            get {
                return ResourceManager.GetString("itemChoicesTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date.
        /// </summary>
        public static string itemExpirationDate {
            get {
                return ResourceManager.GetString("itemExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration time.
        /// </summary>
        public static string itemExpirationTime {
            get {
                return ResourceManager.GetString("itemExpirationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Id.
        /// </summary>
        public static string itemId {
            get {
                return ResourceManager.GetString("itemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string itemName {
            get {
                return ResourceManager.GetString("itemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Price.
        /// </summary>
        public static string itemPrice {
            get {
                return ResourceManager.GetString("itemPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Warehouse.
        /// </summary>
        public static string itemProductWarehouses {
            get {
                return ResourceManager.GetString("itemProductWarehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Quantity.
        /// </summary>
        public static string itemQuantity {
            get {
                return ResourceManager.GetString("itemQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Sale Type.
        /// </summary>
        public static string itemSaleType {
            get {
                return ResourceManager.GetString("itemSaleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item state.
        /// </summary>
        public static string itemState {
            get {
                return ResourceManager.GetString("itemState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributed.
        /// </summary>
        public static string itemStateDistributed {
            get {
                return ResourceManager.GetString("itemStateDistributed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Warehouse.
        /// </summary>
        public static string itemStateInWarehouse {
            get {
                return ResourceManager.GetString("itemStateInWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared for Distribution.
        /// </summary>
        public static string itemStatePreDistributed {
            get {
                return ResourceManager.GetString("itemStatePreDistributed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied.
        /// </summary>
        public static string itemStateSupplied {
            get {
                return ResourceManager.GetString("itemStateSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type.
        /// </summary>
        public static string itemType {
            get {
                return ResourceManager.GetString("itemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item VIN.
        /// </summary>
        public static string itemVin {
            get {
                return ResourceManager.GetString("itemVin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        public static string itemWarehouses {
            get {
                return ResourceManager.GetString("itemWarehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To short login.
        /// </summary>
        public static string loginLengthErrorMsg {
            get {
                return ResourceManager.GetString("loginLengthErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string loginName {
            get {
                return ResourceManager.GetString("loginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your login.
        /// </summary>
        public static string loginRequiredErrorMsg {
            get {
                return ResourceManager.GetString("loginRequiredErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string manageButton {
            get {
                return ResourceManager.GetString("manageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trza commitować resources bo potem ludziom błędy się sypią.
        /// </summary>
        public static string nameOfEStore {
            get {
                return ResourceManager.GetString("nameOfEStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trza commitować resources bo potem ludziom błędy się sypią.
        /// </summary>
        public static string nameOfEStoreCategory {
            get {
                return ResourceManager.GetString("nameOfEStoreCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of new Safety Point.
        /// </summary>
        public static string NameOfSafetyPoint {
            get {
                return ResourceManager.GetString("NameOfSafetyPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Point Group Name.
        /// </summary>
        public static string NameOfSafetyPointGroup {
            get {
                return ResourceManager.GetString("NameOfSafetyPointGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Points that are in Safety Point Group.
        /// </summary>
        public static string NameOfSafetyPointsInSafetyPointGroup {
            get {
                return ResourceManager.GetString("NameOfSafetyPointsInSafetyPointGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameOfSpecyficWarehouse {
            get {
                return ResourceManager.GetString("NameOfSpecyficWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse name.
        /// </summary>
        public static string NameOfWarehouse {
            get {
                return ResourceManager.GetString("NameOfWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record in table.
        /// </summary>
        public static string NameRecordInTable {
            get {
                return ResourceManager.GetString("NameRecordInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of safety point.
        /// </summary>
        public static string NameTypeOfSafetyPoint {
            get {
                return ResourceManager.GetString("NameTypeOfSafetyPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string newPasswordName {
            get {
                return ResourceManager.GetString("newPasswordName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Safety Point created successfull..
        /// </summary>
        public static string newSafetyPointCreated {
            get {
                return ResourceManager.GetString("newSafetyPointCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string noButton {
            get {
                return ResourceManager.GetString("noButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selected items. Please choose some..
        /// </summary>
        public static string noSelectedItems {
            get {
                return ResourceManager.GetString("noSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Items in Specyfic Warehouse..
        /// </summary>
        public static string NumberOfItemsInWarehouse {
            get {
                return ResourceManager.GetString("NumberOfItemsInWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many Safety Points are in this Group.
        /// </summary>
        public static string NumberOfSafetyPointsInGroup {
            get {
                return ResourceManager.GetString("NumberOfSafetyPointsInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many Users are in this Group.
        /// </summary>
        public static string NumberOfUsersInGroup {
            get {
                return ResourceManager.GetString("NumberOfUsersInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string oldPasswordName {
            get {
                return ResourceManager.GetString("oldPasswordName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string paid {
            get {
                return ResourceManager.GetString("paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string passwordLength {
            get {
                return ResourceManager.GetString("passwordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string passwordName {
            get {
                return ResourceManager.GetString("passwordName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password..
        /// </summary>
        public static string passwordRequiredErrorMsg {
            get {
                return ResourceManager.GetString("passwordRequiredErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Way of payment.
        /// </summary>
        public static string payment {
            get {
                return ResourceManager.GetString("payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canot edit already performed Distribution..
        /// </summary>
        public static string performedDistributionEditError {
            get {
                return ResourceManager.GetString("performedDistributionEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string phoneNumber {
            get {
                return ResourceManager.GetString("phoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This information is private.
        /// </summary>
        public static string privateInformation {
            get {
                return ResourceManager.GetString("privateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Warehouses.
        /// </summary>
        public static string ProductWarehouses {
            get {
                return ResourceManager.GetString("ProductWarehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice provider.
        /// </summary>
        public static string provider {
            get {
                return ResourceManager.GetString("provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Address.
        /// </summary>
        public static string providerAddress {
            get {
                return ResourceManager.GetString("providerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Bank Account Number.
        /// </summary>
        public static string providerBankAccountNumber {
            get {
                return ResourceManager.GetString("providerBankAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Bank Info.
        /// </summary>
        public static string providerBankInfo {
            get {
                return ResourceManager.GetString("providerBankInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Info.
        /// </summary>
        public static string providerInfo {
            get {
                return ResourceManager.GetString("providerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Name.
        /// </summary>
        public static string providerName {
            get {
                return ResourceManager.GetString("providerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Name field is required.
        /// </summary>
        public static string providerNameRequiredErrorMsg {
            get {
                return ResourceManager.GetString("providerNameRequiredErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider NIP.
        /// </summary>
        public static string providerNIP {
            get {
                return ResourceManager.GetString("providerNIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of realization.
        /// </summary>
        public static string realizationTime {
            get {
                return ResourceManager.GetString("realizationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of realization field is required.
        /// </summary>
        public static string realizationTimeRequiredErrorMsg {
            get {
                return ResourceManager.GetString("realizationTimeRequiredErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Reciver.
        /// </summary>
        public static string reciver {
            get {
                return ResourceManager.GetString("reciver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reciver field is required.
        /// </summary>
        public static string reciverRequiredErrorMsg {
            get {
                return ResourceManager.GetString("reciverRequiredErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remain.
        /// </summary>
        public static string remain {
            get {
                return ResourceManager.GetString("remain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember?.
        /// </summary>
        public static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error accured. Please try again later..
        /// </summary>
        public static string removedError {
            get {
                return ResourceManager.GetString("removedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this Safety Point from Group.
        /// </summary>
        public static string RemoveSafetyPointFromGroup {
            get {
                return ResourceManager.GetString("RemoveSafetyPointFromGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove user from this Safety Point Group.
        /// </summary>
        public static string RemoveUserFromSafetyPointGroup {
            get {
                return ResourceManager.GetString("RemoveUserFromSafetyPointGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove user from Safety Point Group.
        /// </summary>
        public static string RemoveUserSafetyPointGroup {
            get {
                return ResourceManager.GetString("RemoveUserSafetyPointGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        public static string requiredErrorMsg {
            get {
                return ResourceManager.GetString("requiredErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return item error.
        /// </summary>
        public static string returnItemError {
            get {
                return ResourceManager.GetString("returnItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return item success..
        /// </summary>
        public static string returnItemSuccess {
            get {
                return ResourceManager.GetString("returnItemSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User role name.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choices of Groups for user to add.
        /// </summary>
        public static string SafetyPointGroupChoicesToAdd {
            get {
                return ResourceManager.GetString("SafetyPointGroupChoicesToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to read.
        /// </summary>
        public static string SafetyPointRead {
            get {
                return ResourceManager.GetString("SafetyPointRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to write.
        /// </summary>
        public static string SafetyPointWrite {
            get {
                return ResourceManager.GetString("SafetyPointWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string salary {
            get {
                return ResourceManager.GetString("salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string saveChanges {
            get {
                return ResourceManager.GetString("saveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select this field..
        /// </summary>
        public static string SelectErrorMsg {
            get {
                return ResourceManager.GetString("SelectErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---Choose---.
        /// </summary>
        public static string SelectListChooseItem {
            get {
                return ResourceManager.GetString("SelectListChooseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectListTypesOfSafetyPoints.
        /// </summary>
        public static string SelectListTypesOfSafetyPoints {
            get {
                return ResourceManager.GetString("SelectListTypesOfSafetyPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Safety Point table..
        /// </summary>
        public static string SelectSafetyPointInTable {
            get {
                return ResourceManager.GetString("SelectSafetyPointInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose type of this Safety Point..
        /// </summary>
        public static string SelectTypeOfSafetyPoint {
            get {
                return ResourceManager.GetString("SelectTypeOfSafetyPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services Warehouses.
        /// </summary>
        public static string ServiceWarehouses {
            get {
                return ResourceManager.GetString("ServiceWarehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum Of Tax.
        /// </summary>
        public static string sumOfTax {
            get {
                return ResourceManager.GetString("sumOfTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum Without Tax.
        /// </summary>
        public static string sumWithoutTax {
            get {
                return ResourceManager.GetString("sumWithoutTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum With Tax.
        /// </summary>
        public static string sumWithTax {
            get {
                return ResourceManager.GetString("sumWithTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Name.
        /// </summary>
        public static string taxName {
            get {
                return ResourceManager.GetString("taxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Name is required..
        /// </summary>
        public static string taxNameRequiredErrorMsg {
            get {
                return ResourceManager.GetString("taxNameRequiredErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Value.
        /// </summary>
        public static string taxValue {
            get {
                return ResourceManager.GetString("taxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Value is required..
        /// </summary>
        public static string taxValueRequiredErrorMsg {
            get {
                return ResourceManager.GetString("taxValueRequiredErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price.
        /// </summary>
        public static string totalPrice {
            get {
                return ResourceManager.GetString("totalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user&apos;s Safety Point Groups.
        /// </summary>
        public static string UserCurrentSafetyPointGroups {
            get {
                return ResourceManager.GetString("UserCurrentSafetyPointGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User eMail.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this login exists. Try another name..
        /// </summary>
        public static string userExists {
            get {
                return ResourceManager.GetString("userExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrond Login..
        /// </summary>
        public static string wrongLogInError {
            get {
                return ResourceManager.GetString("wrongLogInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yesButton {
            get {
                return ResourceManager.GetString("yesButton", resourceCulture);
            }
        }
    }
}
